version: 2
jobs:
   build:
     working_directory: ~/cra-generate
     docker:
       - image: circleci/node:6
     steps:
       - checkout
       - run:
          name: Install dependencies
          command: yarn
       - run:
          name: Test
          command: yarn test
